#!/usr/bin/env bash
set -eou

GREEN='\033[1;32m'
YELLOW='\033[1;33m'
NC='\033[0m'

SYSTEM_TYPE="aarch64-darwin"
FLAKE_SYSTEM="darwinConfigurations.${SYSTEM_TYPE}.system"

theme=
touch .theme

if grep -q light .theme; then
	echo "${YELLOW}Switching to dark mode...${NC}"
	theme=dark
	sed -i '' 's/background = "light"/background = "dark"/' ~/code/nix-cfg/modules/shared/config/nvim/lua/plugins/astrocore.lua
	sed -i '' 's/gruvbox-light/gruvbox-dark/' ~/code/nix-cfg/modules/shared/home-manager.nix
	sed -i '' 's/GruvboxMaterialLight/GruvboxMaterialDark/' ~/code/nix-cfg/modules/shared/home-manager.nix
else
	echo "${YELLOW}Switching to light mode...${NC}"
	theme=light
	sed -i '' 's/background = "dark"/background = "light"/' ~/code/nix-cfg/modules/shared/config/nvim/lua/plugins/astrocore.lua
	sed -i '' 's/gruvbox-dark/gruvbox-light/' ~/code/nix-cfg/modules/shared/home-manager.nix
	sed -i '' 's/GruvboxMaterialDark/GruvboxMaterialLight/' ~/code/nix-cfg/modules/shared/home-manager.nix
fi

echo "${YELLOW}Rebuilding nix-darwin...${NC}"
nix --extra-experimental-features 'nix-command flakes' build .#$FLAKE_SYSTEM $@
./result/sw/bin/darwin-rebuild switch --flake .#${SYSTEM_TYPE} $@
unlink ./result
echo "${YELLOW}Restarting kitty...${NC}"
kitten @ load-config

# record current theme
echo $theme >.theme
echo "${GREEN}Toggled theme successfully!${NC}"
